# Generated by Django 6.0.2 on 2026-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='due_date',
            field=models.DateField(blank=True, help_text='Optional due date', null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
